project:
  type: book

lang: pt-BR

book:
  title: "Aplicações de Ciência de Dados"
  author: "Magno T. F. Severino"
  date: "03/02/2026"
  chapters:
    - index.qmd
    - 01_analise_descritiva.qmd
    - part: Classificação
      chapters:
        # - 02_classificacao.qmd
        - 02_classificacao_manutencao_preventiva.qmd
    # - summary.qmd
    # - references.qmd

# bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    number-sections: true
    number-depth: 3
  # pdf:
  #   documentclass: scrreprt

editor: source

